//book
export const GET_BOOK_DATA_REQUEST = "GET_BOOK_DATA_REQUEST";
export const GET_BOOK_DATA_SUCCESS = "GET_BOOK_DATA_SUCCESS";
export const GET_BOOK_DATA_FAILURE = "GET_BOOK_DATA_FAILURE";

//video
export const GET_VIDEO_DATA_REQUEST = "GET_VIDEO_DATA_REQUEST";
export const GET_VIDEO_DATA_SUCCESS = "GET_VIDEO_DATA_SUCCESS";
export const GET_VIDEO_DATA_FAILURE = "GET_VIDEO_DATA_FAILURE";

//acticle
export const GET_ARTICLE_DATA_REQUEST = "GET_ARTICLE_DATA_REQUEST";
export const GET_ARTICLE_DATA_SUCCESS = "GET_ARTICLE_DATA_SUCCESS";
export const GET_ARTICLE_DATA_FAILURE = "GET_ARTICLE_DATA_FAILURE";
export const GET_ARTICLE_ID = "GET_ARTICLE_ID";
